FROM php:7.3.24-apache-stretch
RUN apt-get update -q && apt-get upgrade -yq \
    && apt-get install -yq \
        libpng-dev \
        libjpeg-dev \
        libldap2-dev \
        libxml2-dev \
        mysql-client \
	unzip \
	libzip-dev \
	nano \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
    && docker-php-ext-install calendar mysqli pdo pdo_mysql gd soap zip \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
    && docker-php-ext-install ldap

RUN mkdir /tmp/dolibarr && cd /tmp/dolibarr && \
    curl -o dolibarr.tar.gz -L "https://sourceforge.net/projects/dolibarr/files/Dolibarr%20ERP-CRM/12.0.3/dolibarr-12.0.3.tgz" && \
    tar -xzf dolibarr.tar.gz && \
    rm dolibarr.tar.gz && \
    rm -fr /var/www/html && \
    mv dolibarr-12.0.3 /var/www/html && \
    apt-get clean && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /tmp/dolibarr

RUN curl -o composer -sL https://getcomposer.org/composer.phar && \curl -o composer -sL https://getcomposer.org/composer.phar && \ 
    cd /var/www/html && php composer install

# install mariadb
RUN apt-get update && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y mariadb-server && \

    RUN sed -i 's/bind-address/bind-address = 0.0.0.0 #/i' /etc/mysql/mariadb.conf.d/50-server.cnfRUN sed -i 's/bind-address/bind-address = 0.0.0.0 #/i' /etc/mysql/mariadb.conf.d/50-server.cnf
    echo "mysqld_safe &" > /tmp/config && \
    echo "mysqladmin --silent --wait=30 ping || exit 1" >> /tmp/config && \
    echo "mysql -e 'GRANT ALL PRIVILEGES ON *.* TO \"root\"@\"%\" WITH GRANT OPTION;'" >> /tmp/config && \
    bash /tmp/config && \
    rm -f /tmp/config
